# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomerge < Formula
  desc "Gomerge is a tool to quickly merge several pull requests from your terminal. The intention of this tool is to simplfy, and eventually automate the merging of github pull requests. This tool should be able to run on most systems.
"
  homepage "https://github.com/Cian911/gomerge"
  version "1.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Cian911/gomerge/releases/download/1.1.1/gomerge_1.1.1_Darwin_x86_64.tar.gz"
    sha256 "df585848c512aa3b0c127c11b707f37d792a11918f018253889d4c0f6be6caba"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Cian911/gomerge/releases/download/1.1.1/gomerge_1.1.1_Linux_x86_64.tar.gz"
    sha256 "20fdbf633b6f295b40bb0dd247189cd14eb6e113ce88cad32a6e088421f0c76f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Cian911/gomerge/releases/download/1.1.1/gomerge_1.1.1_Linux_arm64.tar.gz"
    sha256 "62d90d41959397114350bd31dca0f9248569820de7e78187a509ffbcc3e4c3ec"
  end

  def install
    bin.install "gomerge"
  end
end
